[project]
name = "Critical Hit Only"
version = "1.0"
authors = [{ name = "youdietoo" }]
description = """\
You can only deal damage with critical hits.
No, Saturn has no critical hit spot."""

[tool.sdkmod]
name = "Critical Hit Only"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }